remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: 2024 Seattle University Eye Gaze Research

baseurl: https://spammusubi153.github.io/SUEyegazeResearch/

links:
  paper_link: https://cloud.maxopolyworldnews.com/index.php/s/S7Dy98SY9k5P3Jz
  research_comments_link: https://cloud.maxopolyworldnews.com/index.php/s/KcrFAPJ8PtezgTt
  